## alacritty configuration

# theme
import = [
  "~/.config/alacritty/themes/ayu_light.toml"
]

# shell
shell = "/bin/zsh"

# window
[window]
padding = { x = 10, y = 10 }

# font
[font]
normal = { family = "Sarasa Fixed J", style = "SemiBold" }
size = 14
# offset = { x = 1, y = 1 }
# glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = false

# color
[colors]
cursor = { text = "CellForeground" ,cursor = "#FFAA33" }
vi_mode_cursor = { text = "CellForeground", cursor = "#FFAA33" }
draw_bold_text_with_bright_colors = true

# cursor
[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style.shape = "Block"
blink_interval = 500
blink_timeout = 0
unfocused_hollow = false
